---
# PL_Shard -- using PL Proxy to shard requests across databases.

- name: create our test user
  shell: createuser -s {{ shard_user_name }}


# 1. Create each database we know about on each host we know about.

# 2. Create the plproxy schema on each database

# 3. Create the sharded table(s)

# 4. Create shard/batch functions for each database.
